### ISSUE TITLE
FireFly Data Exchange 1.3 was not released

### ISSUE THREAD

**Issue by SamMayWork** [hyperledger/firefly-dataexchange-https#81]
The current release for this microservice is 1.2 with a 1.3.0-rc1 pre-release, we need to make sure that the full 1.3 version is released, this is a blocker for this PR https://github.com/hyperledger/firefly-helm-charts/pull/76

**Comment by awrichar** [comment]
https://github.com/hyperledger/firefly-dataexchange-https/releases/tag/v1.3.0

**Comment by EnriqueL8** [comment]
Yeah I did this one
